### ISSUE TITLE
Inner Ajax Error: Internal Server Error

### ISSUE THREAD

**Issue by morgycatt** [BobRay/RefreshCache#2]
Hi Bob,

I just updated your RefreshCache plugin today, and I'm getting the error "Inner Ajax Error: Internal Server Error" when I try and run it.

Running MODX version 2.7.0, and the server is PHP ver 5.4.45 (so it allowed me to install Guzzle 6 OK)

Do you know what the problem might be please?

Just to note, the website has been running the previous version of your plugin very well for a good few years now - so many thanks for the code - it's been an essential plugin get our client site running speedily - so we really need the new version to work, or at very least a means of a rollback.

many thanks

Ian,

**Comment by BobRay** [comment]
That's difficult to diagnose. The odds are good that the error is occurring inside the Guzzle code.
I wasn't able to test the new version on PHP 5.4, because I have PHP 7 everywhere, so it's possible that upgrading to PHP 7 would fix things.

You should have the option of reverting to the previous version of RefreshCache in Package Manager.  Just uninstalling the current version should do it.

To diagnose the problem, you could try this:

Fire up Chrome Dev. Tools (Ctrl-Shift-I).
Watch the network tab.
Click on the  connector.php call just before the error.
Look at the response tab at the top of the grid.

If there is a response, you  may see an ugly HTML section that might contain a PHP error message.

**Comment by morgycatt** [comment]
Hi Bob,

Many thanks for the reply.

It turns out the PHP version was the problem.

I observed using Chrome dev tools that the code was successfully pulling in the page list JSON  data, but there were no clues as to why it then stopped.

I took a copy of the client's website and built it on our development server, and confirmed the plugin failed on PHP 5.4.x
And then when I toggled the php version to to 5.6 it worked fine, and then also tested and worked fine on php 7.2.15

So I'm now in the process of rolling back the plugin to the previous version until our client is able to update his server.

Many thanks again for the advice.

regards

Ian
